language: cpp
dist: trusty
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
    - cmake
    - libxdamage-dev
    - libx11-dev
    - libxft-dev
    - libxext-dev
    - libglib2.0-dev
    - libxml2-dev
    - libcurl4-gnutls-dev
    - liblua5.1-0-dev
    - libtolua++5.1-dev
    - libcairo2-dev
    - libimlib2-dev
    - libxinerama-dev
    - gawk
    - clang-5.0
    - clang-format-5.0
before_script:
  - mkdir build && cd build && scan-build -o scanbuildout cmake .. && make format-check && cd ..
  - mkdir build-no-x11 && cd build-no-x11 && scan-build -o scanbuildout cmake -DBUILD_X11=OFF .. && make format-check && cd ..
script:
  - cd build && scan-build -o scanbuildout make -j4 && cd ..
  - cd build-no-x11 && scan-build -o scanbuildout make -j4 && cd ..
branches:
  only:
    - master
sudo: false
